version: '3'
services:
  postgresql:
    image: postgres
    container_name: lesson
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_USER=medium_clone
      - POSTGRES_PASSWORD=123
      - POSTGRES_DATABASE=medium_clone
    command: postgres
    restart: always
