version: '3'
services:
  postgres:
    image: postgres
    container_name: medium_clone_backend
    environment:
      POSTGRES_DB: medium_clone
      POSTGRES_USER: medium_clone
      POSTGRES_PASSWORD: 123
    ports:
      - "5432:5432"
    restart: always
